apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-enterprise-core.yaml
  - secret-template.yaml
  - resourcequota.yaml
  - enterprise-core-deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - ingress.yaml
