apiVersion: v1
kind: ResourceQuota
metadata:
  name: shield-intelligence-quota
  namespace: shield-intelligence
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 8Gi
    pods: "28"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shield-observability-quota
  namespace: shield-observability
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 12Gi
    pods: "36"
