import type {
  Account,
  ActiveSession,
  ApiAccessEvent,
  AuditLog,
  Beneficiary,
  ComplianceControl,
  DashboardSummary,
  Finding,
  GapAnalysisItem,
  Incident,
  PrivacyProfile,
  Report,
  RiskMatrixCell,
  SecurityEvent,
  SegmentationPath,
  SpendingPoint,
  TimelineEvent,
  Transaction,
} from "@/lib/types";

export const mockSummary: DashboardSummary = {
  walletBalance: 48275000,
  monthlySpending: 12840000,
  privacyScore: 88,
  securityScore: 84,
  complianceScore: 82,
  openFindings: 7,
  suspiciousEvents: 12,
  transactionVolume: 1895000000,
};

export const mockAccounts: Account[] = [
  {
    id: "acct-wallet-01",
    type: "Primary Wallet",
    name: "Dana Shield Wallet",
    maskedNumber: "DSW-4219-****-8831",
    bank: "Dana Sejahtera Wallet",
    status: "active",
    balance: 48275000,
    currency: "IDR",
    classification: "Confidential",
    lastActivity: "2026-05-28T06:14:00.000Z",
  },
  {
    id: "acct-savings-02",
    type: "Savings Pocket",
    name: "Emergency Reserve",
    maskedNumber: "DSP-7194-****-2048",
    bank: "Dana Sejahtera Wallet",
    status: "active",
    balance: 136000000,
    currency: "IDR",
    classification: "Confidential",
    lastActivity: "2026-05-25T11:42:00.000Z",
  },
  {
    id: "acct-bank-03",
    type: "Linked Bank",
    name: "Payroll Source",
    maskedNumber: "014-****-****-6721",
    bank: "Bank Nusantara",
    status: "review",
    balance: 0,
    currency: "IDR",
    classification: "Sensitive Personal Data",
    lastActivity: "2026-05-22T08:11:00.000Z",
  },
  {
    id: "acct-escrow-04",
    type: "Escrow",
    name: "Merchant Settlement Hold",
    maskedNumber: "ESC-8801-****-1120",
    bank: "Dana Sejahtera Settlement",
    status: "pending",
    balance: 21750000,
    currency: "IDR",
    classification: "Confidential",
    lastActivity: "2026-05-27T17:39:00.000Z",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "TRX-20260528-8831",
    accountId: "acct-wallet-01",
    merchant: "Kopi Ampera",
    category: "Food and beverage",
    amount: 78000,
    currency: "IDR",
    direction: "out",
    status: "settled",
    occurredAt: "2026-05-28T04:21:00.000Z",
    channel: "QRIS",
    risk: "low",
  },
  {
    id: "TRX-20260528-1270",
    accountId: "acct-wallet-01",
    merchant: "Payroll PT. Dana Sejahtera",
    category: "Salary",
    amount: 18500000,
    currency: "IDR",
    direction: "in",
    status: "settled",
    occurredAt: "2026-05-28T02:03:00.000Z",
    channel: "Bank Transfer",
    risk: "low",
  },
  {
    id: "TRX-20260527-7604",
    accountId: "acct-wallet-01",
    merchant: "Sarana Digital",
    category: "Electronics",
    amount: 7250000,
    currency: "IDR",
    direction: "out",
    status: "review",
    occurredAt: "2026-05-27T16:32:00.000Z",
    channel: "Virtual Account",
    risk: "high",
    suspiciousReason: "New beneficiary, high amount, device trust challenge failed once.",
  },
  {
    id: "TRX-20260526-4421",
    accountId: "acct-savings-02",
    merchant: "Dana Savings Pocket",
    category: "Internal transfer",
    amount: 5000000,
    currency: "IDR",
    direction: "out",
    status: "settled",
    occurredAt: "2026-05-26T09:10:00.000Z",
    channel: "Wallet",
    risk: "low",
  },
  {
    id: "TRX-20260525-3398",
    accountId: "acct-wallet-01",
    merchant: "Sentra Kesehatan",
    category: "Health",
    amount: 425000,
    currency: "IDR",
    direction: "out",
    status: "settled",
    occurredAt: "2026-05-25T12:48:00.000Z",
    channel: "QRIS",
    risk: "medium",
  },
  {
    id: "TRX-20260524-9012",
    accountId: "acct-wallet-01",
    merchant: "Unknown Virtual Account",
    category: "Transfer",
    amount: 12600000,
    currency: "IDR",
    direction: "out",
    status: "blocked",
    occurredAt: "2026-05-24T23:19:00.000Z",
    channel: "Virtual Account",
    risk: "critical",
    suspiciousReason: "Velocity rule and impossible travel signal blocked the transfer before settlement.",
  },
  {
    id: "TRX-20260523-1189",
    accountId: "acct-wallet-01",
    merchant: "Moda Raya Transit",
    category: "Transport",
    amount: 38000,
    currency: "IDR",
    direction: "out",
    status: "settled",
    occurredAt: "2026-05-23T01:15:00.000Z",
    channel: "QRIS",
    risk: "low",
  },
  {
    id: "TRX-20260522-7725",
    accountId: "acct-wallet-01",
    merchant: "Merchant Settlement",
    category: "Refund",
    amount: 310000,
    currency: "IDR",
    direction: "in",
    status: "pending",
    occurredAt: "2026-05-22T08:40:00.000Z",
    channel: "Wallet",
    risk: "medium",
  },
];

export const mockBeneficiaries: Beneficiary[] = [
  { id: "ben-01", accountId: "ACC-NADIA-001", name: "Nadia Prameswari", bank: "Dana Sejahtera Wallet", maskedAccount: "8800-****-****-0003", trustLevel: "trusted" },
  { id: "ben-02", accountId: "ACC-MERCHANT-001", name: "Arman Saputra", bank: "Dana Sejahtera Settlement", maskedAccount: "9900-****-****-0001", trustLevel: "review" },
  { id: "ben-03", accountId: "ACC-MERCHANT-001", name: "PT Kreasi Amanah", bank: "Dana Sejahtera Settlement", maskedAccount: "9900-****-****-0001", trustLevel: "new" },
];

export const mockSpendingSeries: SpendingPoint[] = [
  { month: "Jan", spending: 9600000, income: 18200000 },
  { month: "Feb", spending: 11250000, income: 18100000 },
  { month: "Mar", spending: 10800000, income: 18500000 },
  { month: "Apr", spending: 12120000, income: 18400000 },
  { month: "May", spending: 12840000, income: 18500000 },
  { month: "Jun", spending: 7400000, income: 0 },
];

export const mockPrivacyProfile: PrivacyProfile = {
  customerId: "CUST-8842",
  displayName: "Maya Kusuma",
  maskedNik: "3174********8842",
  maskedPhone: "+62 812 **** 4470",
  emailAlias: "maya.kusuma+shield@example.test",
  biometricStatus: "Template enrolled",
  retentionStatus: "Core identity data retained for active-account statutory period.",
  deletionRequestStatus: "No active deletion request. Previous access request completed on 2026-04-19.",
  dataCategories: [
    {
      name: "NIK and identity attributes",
      classification: "Sensitive Personal Data",
      location: "Identity vault",
      retention: "Active account plus legal retention period",
      accessPolicy: "Customer, KYC service, compliance officer with reason",
    },
    {
      name: "Linked bank account metadata",
      classification: "Sensitive Personal Data",
      location: "Payment tokenization store",
      retention: "Until unlink plus settlement audit retention",
      accessPolicy: "Payment service and fraud operations with ticket",
    },
    {
      name: "Biometric template metadata",
      classification: "Sensitive Personal Data",
      location: "Biometric provider token store",
      retention: "Until biometric login disabled",
      accessPolicy: "Authentication service only",
    },
    {
      name: "Transaction history",
      classification: "Confidential",
      location: "Ledger and reporting warehouse",
      retention: "Financial audit retention period",
      accessPolicy: "Customer, ledger service, fraud operations",
    },
    {
      name: "Audit access logs",
      classification: "Internal",
      location: "Immutable audit log store",
      retention: "Security monitoring period",
      accessPolicy: "Security operations and compliance",
    },
  ],
  consents: [
    { id: "CONS-001", purpose: "KYC identity verification", status: "granted", grantedAt: "2026-01-15T04:20:00.000Z", retention: "Required for active account" },
    { id: "CONS-002", purpose: "Fraud monitoring and transaction risk scoring", status: "granted", grantedAt: "2026-01-15T04:25:00.000Z", retention: "Security monitoring period" },
    { id: "CONS-003", purpose: "Personalized merchant offers", status: "revoked", grantedAt: "2026-03-02T09:12:00.000Z", retention: "Purged from campaign audience" },
    { id: "CONS-004", purpose: "Biometric login convenience", status: "pending-review", grantedAt: "2026-05-20T13:05:00.000Z", retention: "Review pending after device reset" },
  ],
};

export const mockSessions: ActiveSession[] = [
  { id: "sess-01", device: "iPhone 15, Dana Shield app", location: "Jakarta, ID", ip: "10.20.7.14", lastSeen: "2026-05-28T06:08:00.000Z", trusted: true, mfa: true },
  { id: "sess-02", device: "Chrome on Windows", location: "Bandung, ID", ip: "10.20.9.88", lastSeen: "2026-05-27T21:12:00.000Z", trusted: true, mfa: true },
  { id: "sess-03", device: "Safari on macOS", location: "Surabaya, ID", ip: "10.21.4.51", lastSeen: "2026-05-24T23:20:00.000Z", trusted: false, mfa: false },
];

export const mockSecurityEvents: SecurityEvent[] = [
  {
    id: "SEC-1001",
    event: "Sensitive value reveal challenged",
    actor: "Maya Kusuma",
    role: "customer",
    source: "profile/privacy",
    timestamp: "2026-05-28T06:18:00.000Z",
    result: "challenged",
    risk: "medium",
    detail: "NIK reveal requires access reason and MFA confirmation.",
  },
  {
    id: "SEC-1002",
    event: "Transaction detail access denied",
    actor: "service:merchant-support",
    role: "service",
    source: "GET /api/v1/fintech/transactions/TRX-20260524-9012",
    timestamp: "2026-05-27T23:42:00.000Z",
    result: "denied",
    risk: "high",
    detail: "Service account requested transaction owned by a different customer context.",
  },
  {
    id: "SEC-1003",
    event: "New device login",
    actor: "Maya Kusuma",
    role: "customer",
    source: "Chrome on Windows",
    timestamp: "2026-05-27T21:12:00.000Z",
    result: "allowed",
    risk: "medium",
    detail: "MFA challenge satisfied, device pending trust review.",
  },
  {
    id: "SEC-1004",
    event: "Admin export policy check",
    actor: "Raka Operations",
    role: "admin",
    source: "reports/export",
    timestamp: "2026-05-26T07:44:00.000Z",
    result: "challenged",
    risk: "high",
    detail: "Export was blocked until encryption evidence was attached.",
  },
];

export const mockComplianceControls: ComplianceControl[] = [
  {
    id: "PDP-01",
    title: "Encryption at rest, in transit, and key evidence",
    score: 86,
    status: "watch",
    owner: "Platform Security",
    summary: "Transport protection is evidenced; exported-report encryption evidence remains partially manual.",
    evidence: ["TLS policy scan", "Database volume encryption attestation", "KMS key rotation ticket KMS-2026-05"],
  },
  {
    id: "PDP-02",
    title: "Access control, least privilege, and audit logging",
    score: 78,
    status: "gap",
    owner: "Security Architecture",
    summary: "Core RBAC is present, but object-level authorization tests show gaps in sandbox evidence.",
    evidence: ["RBAC role inventory", "Denied access audit log", "BOLA validation evidence"],
  },
  {
    id: "PDP-03",
    title: "Breach notification readiness within 3 x 24 hours",
    score: 83,
    status: "watch",
    owner: "Compliance Office",
    summary: "Timeline, affected data categories, and draft notification path are simulated and awaiting management approval.",
    evidence: ["Incident timeline", "Affected-data classification worksheet", "Legal notification checklist"],
  },
];

export const mockGapAnalysis: GapAnalysisItem[] = [
  {
    id: "FIND-001",
    technicalFinding: "Broken object-level authorization on customer profile endpoint",
    impactedData: "NIK, phone, email alias, biometric metadata",
    pdpRequirement: "PDP-02 access control and auditability for personal data access",
    risk: "critical",
    evidence: "Sandbox evidence shows denied and allowed object access comparison.",
    remediation: "Enforce subject ownership and policy decision checks for every object read.",
    status: "open",
  },
  {
    id: "FIND-002",
    technicalFinding: "Missing object-level authorization on transaction detail",
    impactedData: "Transaction IDs, balances, merchant history",
    pdpRequirement: "PDP-02 least privilege and purpose limitation",
    risk: "critical",
    evidence: "API evidence log DS-BOLA-002 maps request owner mismatch to missing decision enforcement.",
    remediation: "Bind transaction resources to customer ID and add deny-by-default authorization middleware.",
    status: "in-progress",
  },
  {
    id: "FIND-003",
    technicalFinding: "Missing encryption evidence for exported report artifacts",
    impactedData: "Compliance reports and sensitive audit excerpts",
    pdpRequirement: "PDP-01 encryption at rest and key management evidence",
    risk: "high",
    evidence: "Export workflow lacks attached KMS proof for one report template.",
    remediation: "Require KMS envelope encryption metadata before report export is marked ready.",
    status: "review",
  },
  {
    id: "FIND-004",
    technicalFinding: "Excessive operations privilege in admin workflow",
    impactedData: "Customer profile summary and incident notes",
    pdpRequirement: "PDP-02 least privilege and role-based access",
    risk: "high",
    evidence: "Operations role can view fields not required for incident triage.",
    remediation: "Split operations roles into transaction monitor and privacy escalations.",
    status: "open",
  },
  {
    id: "FIND-005",
    technicalFinding: "Breach communication approval not yet completed",
    impactedData: "Sensitive personal data notification workflow",
    pdpRequirement: "PDP-03 breach notification within 3 x 24 hours",
    risk: "medium",
    evidence: "Notification countdown remains within window, management approval pending.",
    remediation: "Route simulated incident notification to legal, DPO, and executive approval.",
    status: "pending",
  },
  {
    id: "FIND-006",
    technicalFinding: "Audit log detail insufficient for one sensitive reveal event",
    impactedData: "NIK reveal reason and approver metadata",
    pdpRequirement: "PDP-02 complete audit trail for sensitive personal data access",
    risk: "medium",
    evidence: "One reveal event lacks access reason text in synthetic audit stream.",
    remediation: "Require reason capture before reveal and store immutable reason hash.",
    status: "in-progress",
  },
];

export const mockBreachTimeline: TimelineEvent[] = [
  {
    id: "breach-01",
    time: "2026-05-27T09:05:00.000Z",
    title: "Detection signal opened",
    description: "Suspicious object access pattern raised by the BOLA validation monitor.",
    status: "complete",
  },
  {
    id: "breach-02",
    time: "2026-05-27T10:10:00.000Z",
    title: "Incident classified",
    description: "Privacy impact classified as potential sensitive personal data exposure in the sandbox.",
    status: "complete",
  },
  {
    id: "breach-03",
    time: "2026-05-27T13:35:00.000Z",
    title: "Affected data categories mapped",
    description: "NIK, profile metadata, and transaction references mapped to PDP notification worksheet.",
    status: "complete",
  },
  {
    id: "breach-04",
    time: "2026-05-28T04:40:00.000Z",
    title: "Management approval",
    description: "Executive and legal approval pending before notification package is marked ready.",
    status: "pending",
  },
  {
    id: "breach-05",
    time: "2026-05-30T09:05:00.000Z",
    title: "3 x 24 hours deadline",
    description: "Countdown target for simulated regulator and subject notification readiness.",
    status: "ready",
  },
];

export const mockFindings: Finding[] = [
  {
    id: "FIND-001",
    title: "BOLA on customer profile endpoint",
    severity: "critical",
    cvss: 9.1,
    affectedAsset: "Customer profile API",
    affectedEndpoint: "GET /api/v1/privacy/profile/{customerId}",
    affectedData: "NIK, phone, profile metadata",
    businessImpact: "Unauthorized profile reads could erode trust and trigger privacy response obligations.",
    pdpImpact: "Sensitive personal data access may violate purpose limitation and access-control requirements.",
    reproductionSummary: "Within the lab, a tester compared an owned profile request with a different synthetic customer object and observed an authorization gap in sandbox evidence.",
    evidence: ["DS-BOLA-001 allowed/denied trace pair", "Audit event SEC-1002", "Policy decision log missing owner constraint"],
    remediation: "Enforce object ownership at API middleware and add regression tests for cross-customer object IDs.",
    status: "open",
  },
  {
    id: "FIND-002",
    title: "Missing object-level authorization on transaction detail",
    severity: "critical",
    cvss: 9.0,
    affectedAsset: "Transaction detail service",
    affectedEndpoint: "GET /api/v1/fintech/transactions/{transactionId}",
    affectedData: "Transaction history and account reference",
    businessImpact: "Exposure of transaction patterns could support fraud and customer profiling.",
    pdpImpact: "Financial history is confidential data requiring strict access controls and traceable audit.",
    reproductionSummary: "Safe sandbox evidence compares an allowed owned transaction detail with a denied cross-owner access expectation.",
    evidence: ["DS-BOLA-002 object-owner mismatch", "Synthetic request ID req-7f92", "Denied-state UI regression scenario"],
    remediation: "Bind transaction lookup to both transaction ID and authenticated customer ID.",
    status: "in-progress",
  },
  {
    id: "FIND-003",
    title: "Excessive admin privilege in incident triage",
    severity: "high",
    cvss: 8.0,
    affectedAsset: "Operations console",
    affectedEndpoint: "GET /api/v1/admin/customers",
    affectedData: "Customer identity summary and linked bank metadata",
    businessImpact: "Broad access increases insider-risk blast radius during routine operations.",
    pdpImpact: "Least privilege evidence is incomplete for operations support workflows.",
    reproductionSummary: "Role-mapping review found operations access to fields not required for triage workflows.",
    evidence: ["RBAC matrix export", "Admin workflow screenshot placeholder", "Access review AR-2026-05"],
    remediation: "Split admin scopes and mask bank metadata unless privacy escalation is approved.",
    status: "review",
  },
  {
    id: "FIND-004",
    title: "Weak session timeout for high-risk admin path",
    severity: "medium",
    cvss: 6.4,
    affectedAsset: "Admin portal session policy",
    affectedEndpoint: "POST /api/v1/admin/incidents/{id}/approve",
    affectedData: "Incident status and response workflow",
    businessImpact: "Stale privileged sessions could approve sensitive actions after inactivity.",
    pdpImpact: "Weak control evidence affects accountability for privacy incidents.",
    reproductionSummary: "Lab session policy review found idle timeout exceeds the target for privileged workflows.",
    evidence: ["Session policy SP-ADMIN-02", "Synthetic idle timer evidence", "MFA challenge policy record"],
    remediation: "Reduce admin idle timeout and require step-up MFA for incident approval.",
    status: "open",
  },
  {
    id: "FIND-005",
    title: "Missing encryption evidence for exported report",
    severity: "high",
    cvss: 7.4,
    affectedAsset: "Report export service",
    affectedEndpoint: "POST /api/v1/reports/export",
    affectedData: "Pentest report and PDP gap analysis excerpts",
    businessImpact: "Sensitive report artifacts could be mishandled without encryption attestation.",
    pdpImpact: "PDP-01 evidence is incomplete for generated artifacts.",
    reproductionSummary: "Export workflow generated a placeholder without attached KMS metadata in the simulated report center.",
    evidence: ["Report artifact REP-003", "KMS evidence missing flag", "Governance check GOV-44"],
    remediation: "Require envelope encryption metadata and retention labels before export readiness.",
    status: "pending",
  },
  {
    id: "FIND-006",
    title: "Network segmentation weakness between web and database zone",
    severity: "high",
    cvss: 8.1,
    affectedAsset: "Web to database network path",
    affectedEndpoint: "tcp/5432 segmentation policy",
    affectedData: "Ledger database and audit log store",
    businessImpact: "A compromised web workload could have a broader path to sensitive stores.",
    pdpImpact: "Security safeguards for sensitive personal data require stronger network isolation evidence.",
    reproductionSummary: "Segmentation validation shows one synthetic web workload path marked allowed where policy expects blocked.",
    evidence: ["SEG-006 path result", "Network policy diff placeholder", "Telemetry trace net-2026-05"],
    remediation: "Enforce namespace network policy and allow database access only from API service identity.",
    status: "in-progress",
  },
  {
    id: "FIND-007",
    title: "Insufficient audit detail for sensitive data access",
    severity: "medium",
    cvss: 5.9,
    affectedAsset: "Audit log service",
    affectedEndpoint: "POST /api/v1/audit/logs",
    affectedData: "NIK reveal reason and approver metadata",
    businessImpact: "Investigators may lack context for sensitive reveal events.",
    pdpImpact: "Auditability evidence for sensitive personal data access is incomplete.",
    reproductionSummary: "Synthetic reveal event recorded the action and actor but omitted a structured access reason.",
    evidence: ["Audit log AUD-4105", "Reveal dialog audit preview", "PDP-02 evidence checklist"],
    remediation: "Require purpose, ticket, and data category fields on every sensitive-data reveal event.",
    status: "open",
  },
];

export const mockApiAccessEvents: ApiAccessEvent[] = [
  {
    id: "DS-BOLA-001A",
    endpoint: "/api/v1/privacy/profile/CUST-8842",
    method: "GET",
    actor: "maya.kusuma",
    role: "customer",
    decision: "allowed",
    objectOwner: "CUST-8842",
    requestedObject: "CUST-8842",
    timestamp: "2026-05-28T03:22:00.000Z",
    evidence: "Owned profile access permitted after policy decision.",
  },
  {
    id: "DS-BOLA-001B",
    endpoint: "/api/v1/privacy/profile/CUST-9017",
    method: "GET",
    actor: "maya.kusuma",
    role: "customer",
    decision: "denied",
    objectOwner: "CUST-9017",
    requestedObject: "CUST-9017",
    timestamp: "2026-05-28T03:24:00.000Z",
    evidence: "Expected denied state for cross-customer profile access.",
  },
  {
    id: "DS-BOLA-002A",
    endpoint: "/api/v1/fintech/transactions/TRX-20260528-8831",
    method: "GET",
    actor: "maya.kusuma",
    role: "customer",
    decision: "allowed",
    objectOwner: "CUST-8842",
    requestedObject: "TRX-20260528-8831",
    timestamp: "2026-05-28T03:29:00.000Z",
    evidence: "Owned transaction detail returned masked data.",
  },
  {
    id: "DS-BOLA-002B",
    endpoint: "/api/v1/fintech/transactions/TRX-20260524-9012",
    method: "GET",
    actor: "merchant-support",
    role: "service",
    decision: "challenged",
    objectOwner: "CUST-8842",
    requestedObject: "TRX-20260524-9012",
    timestamp: "2026-05-28T03:31:00.000Z",
    evidence: "Service access requires purpose-bound token and case ID.",
  },
];

export const mockSegmentationPaths: SegmentationPath[] = [
  {
    id: "SEG-001",
    source: "web-public-zone",
    target: "api-private-zone",
    protocol: "HTTPS 443",
    result: "allowed",
    evidence: "Public web can call API gateway through mTLS edge policy.",
    timestamp: "2026-05-28T05:20:00.000Z",
  },
  {
    id: "SEG-002",
    source: "api-private-zone",
    target: "ledger-db-zone",
    protocol: "PostgreSQL 5432",
    result: "allowed",
    evidence: "API service identity is allowed to reach ledger database.",
    timestamp: "2026-05-28T05:22:00.000Z",
  },
  {
    id: "SEG-003",
    source: "web-public-zone",
    target: "ledger-db-zone",
    protocol: "PostgreSQL 5432",
    result: "blocked",
    evidence: "Expected network policy blocks direct web to database path.",
    timestamp: "2026-05-28T05:24:00.000Z",
  },
  {
    id: "SEG-004",
    source: "reports-worker-zone",
    target: "audit-log-zone",
    protocol: "HTTPS 443",
    result: "allowed",
    evidence: "Report worker can read signed audit excerpts through service account.",
    timestamp: "2026-05-28T05:27:00.000Z",
  },
  {
    id: "SEG-006",
    source: "web-public-zone",
    target: "audit-log-zone",
    protocol: "HTTPS 443",
    result: "blocked",
    evidence: "Synthetic validation confirms direct audit-store access is denied.",
    timestamp: "2026-05-28T05:29:00.000Z",
  },
];

export const mockIncidents: Incident[] = [
  {
    id: "INC-2026-051",
    title: "BOLA profile access validation gap",
    severity: "critical",
    affectedSystems: ["Customer profile API", "Privacy profile service"],
    owner: "Siti Rahma",
    sla: "6h response",
    status: "in-progress",
    pdpNotificationRequired: true,
    affectedData: ["Sensitive Personal Data", "Personal Data"],
  },
  {
    id: "INC-2026-052",
    title: "Report export encryption evidence missing",
    severity: "high",
    affectedSystems: ["Report center", "Governance workflow"],
    owner: "Intan Compliance",
    sla: "1 business day",
    status: "review",
    pdpNotificationRequired: false,
    affectedData: ["Confidential"],
  },
  {
    id: "INC-2026-053",
    title: "Suspicious virtual account transfer blocked",
    severity: "medium",
    affectedSystems: ["Fraud rules", "Wallet ledger"],
    owner: "Raka Operations",
    sla: "12h review",
    status: "open",
    pdpNotificationRequired: false,
    affectedData: ["Confidential"],
  },
];

export const mockAuditLogs: AuditLog[] = [
  { id: "AUD-4101", actor: "maya.kusuma", role: "customer", action: "transaction.view", resource: "TRX-20260528-8831", timestamp: "2026-05-28T06:15:00.000Z", result: "success", risk: "low", classification: "Confidential" },
  { id: "AUD-4102", actor: "maya.kusuma", role: "customer", action: "nik.reveal.requested", resource: "privacy-profile:CUST-8842", timestamp: "2026-05-28T06:18:00.000Z", result: "challenged", risk: "medium", classification: "Sensitive Personal Data" },
  { id: "AUD-4103", actor: "merchant-support", role: "service", action: "transaction.view", resource: "TRX-20260524-9012", timestamp: "2026-05-27T23:42:00.000Z", result: "denied", risk: "high", classification: "Confidential" },
  { id: "AUD-4104", actor: "raka.ops", role: "admin", action: "incident.triage", resource: "INC-2026-051", timestamp: "2026-05-27T13:18:00.000Z", result: "success", risk: "medium", classification: "Internal" },
  { id: "AUD-4105", actor: "intan.compliance", role: "auditor", action: "evidence.attach", resource: "PDP-01", timestamp: "2026-05-27T11:05:00.000Z", result: "success", risk: "low", classification: "Confidential" },
  { id: "AUD-4106", actor: "bagas.security", role: "pentester", action: "bola.validation.view", resource: "DS-BOLA-002", timestamp: "2026-05-27T10:44:00.000Z", result: "success", risk: "medium", classification: "Internal" },
  { id: "AUD-4107", actor: "raka.ops", role: "admin", action: "customer.search", resource: "customer-index", timestamp: "2026-05-26T08:29:00.000Z", result: "challenged", risk: "high", classification: "Personal Data" },
  { id: "AUD-4108", actor: "report-worker", role: "service", action: "report.export", resource: "REP-003", timestamp: "2026-05-26T07:44:00.000Z", result: "denied", risk: "high", classification: "Confidential" },
  { id: "AUD-4109", actor: "api-gateway", role: "service", action: "policy.evaluate", resource: "GET /privacy/profile", timestamp: "2026-05-25T18:02:00.000Z", result: "success", risk: "low", classification: "Internal" },
  { id: "AUD-4110", actor: "siti.soc", role: "admin", action: "incident.close", resource: "INC-2026-047", timestamp: "2026-05-24T15:40:00.000Z", result: "success", risk: "low", classification: "Internal" },
];

export const mockReports: Report[] = [
  {
    id: "REP-000",
    title: "Rules of Engagement",
    description: "Authorized scope, testing windows, excluded assets, safety boundaries, contacts, and evidence-handling rules.",
    status: "ready",
    owner: "Security Program Office",
    updatedAt: "2026-05-28T06:10:00.000Z",
    classification: "Internal",
    sections: ["Authorized scope", "Excluded assets", "Safety controls", "Contacts", "Evidence handling"],
    audience: "Pentester, SOC, Compliance",
    controlRefs: ["RoE"],
    exportReadiness: "Approved for demo distribution",
  },
  {
    id: "REP-001",
    title: "Technical Pen-Test Report",
    description: "Detailed technical findings, safe evidence, affected endpoints, CVSS scoring, and remediation notes.",
    status: "in-progress",
    owner: "Bagas Security",
    updatedAt: "2026-05-28T05:44:00.000Z",
    classification: "Confidential",
    sections: ["Scope", "Rules of Engagement", "Findings", "Safe proof of concept", "Remediation"],
    audience: "Security engineering and application owners",
    controlRefs: ["RoE", "CVSS", "PDP-02"],
    exportReadiness: "Pending owner sign-off for two critical findings",
  },
  {
    id: "REP-002",
    title: "Executive Summary",
    description: "Business risk, potential regulatory exposure, customer impact, and remediation progress.",
    status: "ready",
    owner: "Risk Committee",
    updatedAt: "2026-05-28T04:50:00.000Z",
    classification: "Internal",
    sections: ["Risk posture", "Top findings", "Financial exposure", "Decision points"],
    audience: "Board, executives, risk committee",
    controlRefs: ["PDP-01", "PDP-02", "PDP-03"],
    exportReadiness: "Ready with synthetic evidence watermark",
  },
  {
    id: "REP-003",
    title: "UU PDP Gap Analysis",
    description: "Mapping of technical security findings to PDP obligations, evidence quality, and remediation status.",
    status: "review",
    owner: "Intan Compliance",
    updatedAt: "2026-05-27T16:31:00.000Z",
    classification: "Confidential",
    sections: ["PDP-01", "PDP-02", "PDP-03", "Evidence gaps", "Control owners"],
    audience: "DPO, compliance officer, internal audit",
    controlRefs: ["PDP-01", "PDP-02", "PDP-03"],
    exportReadiness: "Requires PDP-01 export encryption attestation",
  },
  {
    id: "REP-004",
    title: "Remediation Roadmap",
    description: "Prioritized engineering roadmap with owners, due dates, dependency notes, and verification criteria.",
    status: "pending",
    owner: "Platform Security",
    updatedAt: "2026-05-27T09:20:00.000Z",
    classification: "Internal",
    sections: ["30 days", "60 days", "90 days", "Verification", "Residual risk"],
    audience: "Engineering leadership and management",
    controlRefs: ["PDP-01", "PDP-02", "PDP-03"],
    exportReadiness: "Draft awaiting roadmap owner approval",
  },
  {
    id: "REP-005",
    title: "Audit Evidence Package",
    description: "Curated audit logs, access-control decisions, breach timeline, encryption evidence, and report export guardrails.",
    status: "review",
    owner: "Intan Compliance",
    updatedAt: "2026-05-28T06:02:00.000Z",
    classification: "Confidential",
    sections: ["Audit logs", "Access decisions", "Encryption proof", "Breach timeline", "Evidence index"],
    audience: "Internal audit and regulator simulation",
    controlRefs: ["PDP-01", "PDP-02", "PDP-03"],
    exportReadiness: "Ready after legal review checklist is complete",
  },
];

export const mockRiskMatrix: RiskMatrixCell[] = [
  { likelihood: "Likely", impact: "Severe", level: "critical", count: 2 },
  { likelihood: "Likely", impact: "Major", level: "high", count: 3 },
  { likelihood: "Possible", impact: "Major", level: "high", count: 2 },
  { likelihood: "Possible", impact: "Moderate", level: "medium", count: 4 },
  { likelihood: "Unlikely", impact: "Moderate", level: "medium", count: 2 },
  { likelihood: "Unlikely", impact: "Minor", level: "low", count: 6 },
];

export const mockSystemHealth = [
  { service: "API gateway", status: "ready", latency: "32 ms", owner: "Platform" },
  { service: "Identity and RBAC", status: "ready", latency: "41 ms", owner: "Security" },
  { service: "Ledger service", status: "ready", latency: "56 ms", owner: "Payments" },
  { service: "Audit log pipeline", status: "watch", latency: "89 ms", owner: "SOC" },
  { service: "Report export", status: "gap", latency: "122 ms", owner: "Compliance" },
];

export const mockCustomers = [
  { id: "CUST-8842", name: "Maya Kusuma", tier: "Gold", status: "active", maskedNik: "3174********8842", risk: "low" },
  { id: "CUST-2170", name: "Ari Wibowo", tier: "Standard", status: "active", maskedNik: "3273********2170", risk: "medium" },
  { id: "CUST-9017", name: "Laras Pertiwi", tier: "Gold", status: "review", maskedNik: "3372********9017", risk: "high" },
  { id: "CUST-1129", name: "Dewa Pranata", tier: "Merchant", status: "active", maskedNik: "3175********1129", risk: "low" },
];

export const mockAdminMetrics = {
  customers: 42880,
  transactionVolume: 1895000000,
  failedLogins: 184,
  suspiciousApiCalls: 29,
  openIncidents: mockIncidents.length,
};

export const mockExecutiveExposure = {
  regulatoryImpact: "Potential PDP notification if exposure is confirmed",
  operationalRisk: "High until object-level authorization remediation is verified",
  financialExposure: 420000000,
  readinessScore: 82,
  remediationProgress: 47,
};
