receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
  resource:
    attributes:
      - key: shield.stage
        value: stage7
        action: upsert

exporters:
  logging:
    verbosity: basic
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging, prometheus]
