apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -local
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: shield-stage7-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: scale-dashboard
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: scale-dashboard
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: scale-dashboard
commonLabels:
  shield.environment: local-lab
