apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -distributed
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: shield-stage7-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
commonLabels:
  shield.environment: distributed-cyber-range
